#!/usr/bin/env sh
#
# Generate list of PIA VPN servers for NixOS module.
#
# Inspired by the pia-nm.sh[1] script.
#
# [1] https://www.privateinternetaccess.com/installer/pia-nm.sh
#
# 2021-06-14: Although the above script still exists, it doesn't work anymore.
# PIA changed their API on how to get server info and didn't update pia-nm.sh.
# The correct URL for getting server info was found in
# https://github.com/pia-foss/manual-connections, file "get_region.sh".

set -e

error() {
    echo "$@" >&2
    exit 1
}

thisfile=$(readlink -f -- "$0")
thisdir=$(dirname "$thisfile")
outputfile="$thisdir/pia-generated-server-list.nix"
IFS=$(echo)
servers=$(curl -Ss "https://serverlist.piaservers.net/vpninfo/servers/v4" | head -1)

if [ -z "$servers" ]; then
    error "Failed to download server list, aborting."
fi

servers=$(python3 <<EOF
import sys
import json
data = json.loads('$servers')

for r in data["regions"]:
    print(r["dns"] + ':' + r["name"])
EOF
)

printf "# Generated by ./$(realpath --relative-to="$PWD" "$thisfile")\n\n" > "$outputfile"
printf "[\n" >> "$outputfile"
echo "$servers" | while read server; do
    name="PIA - "$(echo "$server" | cut -d: -f2)
    host=$(echo "$server" | cut -d: -f1)

    cat <<EOF >> "$outputfile"
  { id = "$name";
    uuid = "$(uuid -v 5 ns:URL "$name-$host")";
    remote = "$host";
  }
EOF
done
printf "]" >> "$outputfile"

echo "Generated $(echo "$servers" | wc -l) server entries in $outputfile"
